### ISSUE TITLE
Running on iOS 

### ISSUE THREAD

**Issue by luke2m** [tulir/mautrix-imessage#1]
This looks awesome — any status or ETA for running on iOS?

**Comment by NSExceptional** [comment]
I'm curious too, because it seems [BeeperHQ](https://beeper.com/) already [uses this](https://gitlab.com/nova?sort=latest_activity_desc&page=1) on [jailbroken iPhones](https://www.reddit.com/r/beeper/comments/ldcbn2/we_are_the_creators_of_beeper_ask_us_anything/gm58ph2?context=10) for iMessage.
