### ISSUE TITLE
Unable to send messages to iMessage client

### ISSUE THREAD

**Issue by chrispruitt** [tulir/mautrix-imessage#2]
Firstly, this project is awesome! Thank you for providing this bridge!

After setting this bridge up, all my iMessage came through properly (except messages sent by my apple id). However, when I tried to reply through Element.io to my home server (i.e. send a message to the iMessage application), the bridge did not seem to pick up the message. I did not see anything in the logs.

Also, (maybe this is related and caused by a configuration issue) but none of my personal iMessages were backfilled into my home server. Nor can I send a message through the iMessage client (from my own apple id to a random iPhone user) and have it show up on my home server. None of my sent iMessages were backfilled into my home server either. Only messages sent from other apple iMessage users.

Any thoughts on this?

EDIT:
Found this in the logs. I missed it before.
```
[Mar 18, 2021 09:41:44] [Portal/iMessage;-;+1000000/DEBUG] Dropping own message in iMessage;-;+10000000 as double puppeting is not initialized
```
So, my question now is, how can i enable double puppeting?

**Comment by tulir** [comment]
The synapse or wsproxy logs will probably contain errors. https://docs.mau.fi/bridges/general/troubleshooting.html

**Comment by chrispruitt** [comment]
It looks like double puppeting was not enabled. Is there a way to enable it?

**Comment by Yumekui** [comment]
I use the [_matrix-synapse-shared-secret-auth_](https://github.com/devture/matrix-synapse-shared-secret-auth) module as described [here](https://docs.mau.fi/bridges/general/double-puppeting.html#automatically).

**Comment by chrispruitt** [comment]
ah thanks for the tip @Yumekui! thats what i was missing
