### ISSUE TITLE
Non-Standard iMessages cause crash (MacOS)

### ISSUE THREAD

**Issue by xcsdm** [tulir/mautrix-imessage#3]
Messaging "Apple" either store or Apple Card causes mautrix-imessage to seg fault

>[0m[Jun  8, 2021 14:26:15] [Matrix/DEBUG] Appservice transaction websocket connected
[0m[Jun  8, 2021 14:26:15] [Matrix/DEBUG] Sending bridge status to server
[36m[Jun  8, 2021 14:26:15] [Portal/iMessage;-;urn:biz:b15ed773-9eed-11e7-baa2-7b88b04daa8e/INFO] Syncing portal[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x44d3aa6]

>goroutine 42 [running]:
maunium.net/go/mautrix/appservice.(*IntentAPI).EnsureRegistered(0x0, 0xc00031424b, 0x2c)
	/Users/along/go/pkg/mod/maunium.net/go/mautrix@v0.9.2-0.20210312135809-77e23d55acb5/appservice/intent.go:55 +0x26
main.(*Portal).CreateMatrixRoom(0xc0003221b0, 0x0, 0x0)
	/Users/along/opt/mautrix-imessage/portal.go:370 +0xcc
main.(*Portal).Sync(0xc0003221b0)
	/Users/along/opt/mautrix-imessage/portal.go:175 +0x318
main.(*Bridge).StartupSync(0xc00012e3c0)
	/Users/along/opt/mautrix-imessage/main.go:308 +0x33d
created by main.(*Bridge).Start
	/Users/along/opt/mautrix-imessage/main.go:286 +0x4da

**Comment by tulir** [comment]
That sounds like you're using an outdated version of hte bridge
